# Site settings
title: A bit of p1st4ch0
email: pistacho@riseup.net
description: "A blog about programming, reverse engineering, and possible tech solutions."
baseurl: ""
url: "http://p1st4ch0.github.io"
twitter_username: p1st4ch0
github_username:  p1st4ch0

# Build settings
markdown: kramdown
permalink: pretty

excerpt_separator: ""
